import Head from 'next/head'

export default function Home() {
  
var CLIENT_ID = '905694888986-jln4ifm94rqi57ktsekiiqqnllsh4rtm.apps.googleusercontent.com'; // Insira o ID do cliente aqui
var API_KEY = 'AIzaSyAiJgKXvvSW4mAmX2_4b-Xb3Ba07Nq7YxA'; // Insira a chave de API aqui
var DISCOVERY_DOCS = ["https://www.googleapis.com/discovery/v1/apis/fitness/v1/rest"];
var SCOPES = 'https://www.googleapis.com/auth/fitness.activity.read';

function handleClientLoad() {
    gapi.client.init({
        apiKey: API_KEY,
        discoveryDocs: DISCOVERY_DOCS,
        clientId: CLIENT_ID,
        scope: SCOPES
    }).then(function () {
        gapi.auth2.getAuthInstance().isSignedIn.listen(updateSigninStatus);
        updateSigninStatus(gapi.auth2.getAuthInstance().isSignedIn.get());
    }, function (error) {
        console.log(JSON.stringify(error, null, 2));
    });
}

function updateSigninStatus(isSignedIn) {
    if (isSignedIn) {
        makeRequest();
    } else {
        gapi.auth2.getAuthInstance().signIn();
    }
}

function makeRequest() {
    var request = gapi.client.request({
        'method': 'GET',
        'path': '/fitness/v1/users/me/dataSources'
    });
    request.execute(function(resp) {
        console.log(resp);
    });
}

  return (
    <>
      <Head>
        <title>Seed Walkers</title>
        <script src="https://accounts.google.com/gsi/client" async defer></script>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <div id="g_id_onload"
          data-client_id="905694888986-jln4ifm94rqi57ktsekiiqqnllsh4rtm.apps.googleusercontent.com"
          data-callback="handleCredentialResponse">
      </div>
      <div class="g_id_signin" data-type="standard"></div>

      <button onClick={handleClientLoad}>Sign in with Google</button>      

    </>
  )
}
